In [ ]:
from google.colab import drive
drive.mount("/content/drive")
%cd /content/drive/MyDrive/Capstone_Accenture4/Data

Mounted at /content/drive
/content/drive/MyDrive/Capstone_Accenture4/Data

#### Dependencies

In [ ]:
import pandas as pd
import numpy as np

#### Data - Manufacturing_value

In [ ]:
data = pd.read_excel('raw/Tab1.xlsx')
data = data[data['Country Code'].notna()]
Country_Codes = list(np.unique(data['Country Code']))

In [ ]:
### Factors for attractiveness in Manufacturing 
Manufacturing_X = ['Air_freight_million_ton_km',
 'Container_port_traffic_TEU',
 'Railways_goods_trans_million_ton-km',
 'Logistic_performance',
 'Industry_value_added_current_USD',
 'GDP_per_capita_current_USD',
 'Final_consumption',
 'Access_finance',
 'New_business_density'
 ]

Manufacturing_y = ['Manufacturing_value added_%_of_GDP']

In [ ]:
with pd.ExcelWriter("Manufacturing.xlsx") as writer:  
  for c in Country_Codes:
    subdata = data[data['Country Code'] == c].reset_index().drop(['index', 'Time'], axis = 1)
    subdata['Year'] = subdata['Time Code'].apply(lambda x: str(x)[2:])
    subdata = subdata.set_index('Year').drop(['Time Code'], axis = 1)
    dic_tab1 = {
        subdata.columns[2]: Manufacturing_X[3],
        subdata.columns[3]: Manufacturing_X[0],
        subdata.columns[4]: Manufacturing_X[1],
        subdata.columns[5]: Manufacturing_X[2],
        subdata.columns[6]: Manufacturing_X[4],
        subdata.columns[7]: Manufacturing_X[5],
        subdata.columns[8]: Manufacturing_X[6],
        subdata.columns[9]: Manufacturing_X[7],
        subdata.columns[10]: Manufacturing_X[8],
        subdata.columns[11]: Manufacturing_y[0]
    }
    subdata = subdata.rename(columns = dic_tab1).drop(['Country Name', 'Country Code'], axis = 1)
    subdata.to_excel(writer,
              sheet_name=c)

#### Data - Service_value

In [ ]:
data2 = pd.read_excel('raw/Tab2.xlsx')
data2 = data2[data2['Country Code'].notna()]
Country_Codes = list(np.unique(data2['Country Code']))

In [ ]:
### Factors for attractiveness in Service 
Service_X = ['Access_electricity',
 'Industry_value_added_current_USD',
 'Employment_in_industry_%_of_total_employment',
 'GDP_per_capita_current_USD',
 'Final_consumption',
 'Primary_completion_rate',
 'Educational_attainment',
 'Individuals_using_the_Internet_%_of_population',
 'Poverty_headcount_ratio',
 'Access_finance',
 'New_business_density'
 ]

Service_y = ['Services_value_added_%_of_GDP']

In [ ]:
with pd.ExcelWriter("Service.xlsx") as writer:  
  for c in Country_Codes:
    subdata = data2[data2['Country Code'] == c].reset_index().drop(['index', 'Time'], axis = 1)
    subdata['Year'] = subdata['Time Code'].apply(lambda x: str(x)[2:])
    subdata = subdata.set_index('Year').drop(['Time Code'], axis = 1)
    dic_tab2 = {
            subdata.columns[2]: Service_X[1],
            subdata.columns[3]: Service_X[0],
            subdata.columns[4]: Service_X[2],
            subdata.columns[5]: Service_X[3],
            subdata.columns[6]: Service_X[4],
            subdata.columns[7]: Service_X[5],
            subdata.columns[8]: Service_X[6],
            subdata.columns[9]: Service_X[7],
            subdata.columns[10]: Service_X[8],
            subdata.columns[11]: Service_X[9],
            subdata.columns[12]: Service_X[10],
            subdata.columns[13]: Service_y[0]
        }
    subdata = subdata.rename(columns = dic_tab2).drop(['Country Name', 'Country Code'], axis = 1)
    subdata.to_excel(writer,
              sheet_name=c)